### ISSUE TITLE
Java Profiler

### ISSUE THREAD

**Issue by pselle** [iopipe/iopipe-java#36]
Add profiling plugin to repo, such that users can profile their Lambda code and download the profiles from IOpipe.

**Comment by XerTheSquirrel** [comment]
Work in progress repository is at <https://github.com/XerTheSquirrel/iopipe-java> in the `feature-plugins` branch. So far there is just one added method in the API which is not breaking, then the internal code (that the user will not be seeing) just spawns the method to execute in another thread so that way the profile has an easier time profiling it.

**Comment by XerTheSquirrel** [comment]
Okay, so I have been refactoring the connection system so that way it can better handle how the profiler would be pushing snapshots to the remote end. The changes should not affect any end user code unless they are doing advanced and custom things with their configuration. The refactoring makes the code much cleaner and definitely improves it (and has less duplicate code). I am very certain that refactoring the connection code would be much better in the long run.

**Comment by XerTheSquirrel** [comment]
The profiler is finished for the most part, it is currently waiting on a few things from the service end.

**Comment by XerTheSquirrel** [comment]
The pull request is in issue #39.

**Comment by XerTheSquirrel** [comment]
And pull request #39 was merged, so closing this issue.
