### ISSUE TITLE
Memory tier should be reported in megabytes, not bytes

### ISSUE THREAD

**Issue by coreylight** [iopipe/iopipe-java#37]
Both python and node report the memory tier in MB, which seems to come directly from aws
https://github.com/iopipe/iopipe-js-core/blob/0b8e2a904791d939302b2cd2fac11a8d230836f0/src/report.js#L44

Not sure why, but it seems like Java is reporting in bytes, even though it's using the aws provided function too?
https://github.com/iopipe/iopipe-java/blob/10bbfb6c79a5d49256198bbcd5dceb037591f567/src/main/java/com/iopipe/IOpipeMeasurement.java#L211

**Comment by XerTheSquirrel** [comment]
Is the value it returns a multiple of 1048576?

This would be an Amazon bug but the value it returns could be passed through a function to potentially transform the value. If the Amazon source code is available for the implementation of the `Context` object it can be seen where it gets its value from. If it is not available then it should still be possible to obtain the class file of the implementation and dump its byte code. The same source of data could be read or a very similar metric so that if the returned value and another are within a given margin of error then consider it to be in bytes or MiB accordingly. This would cover a case where Amazon potentially fixes this bug compared to leaving it alone.

**Comment by coreylight** [comment]
The value returned is `2147483647` which seems to be the multiple.

**Comment by XerTheSquirrel** [comment]
That value is `Integer.MAX_VALUE` which is only used for the `MockContext` used in testing locally. I used that value because there is no real upper limit on the amount of memory that can be used on a local system. The method in `MockContext` could be changed to return a fixed value that is smaller or use an estimate as to the amount of memory available to a system.

On real AWS the returned value is correct in MiB (in this case 128) which I just tested.

**Comment by coreylight** [comment]
Ah! I see. Yes I've been looking at a local invoke.

Serverless framework uses a static number of 1024 for local invocation. I'd probably just go with that for simplicity's sake.
https://github.com/serverless/serverless/blob/d1d1b05cea475810c88aa933e2fe3c95065756b8/lib/plugins/aws/invokeLocal/index.js#L319

**Comment by XerTheSquirrel** [comment]
Okay so I pushed 14d3f01f47c74df0aaa5734f56279e2da80190e6 which just uses `1024` instead.

I suppose this issue should be closed then, hopefully there is no further confusion.
