### ISSUE TITLE
Test IOpipe with Spring Cloud Functions

### ISSUE THREAD

**Issue by pselle** [iopipe/iopipe-java#57]
Show IOpipe (Java) working with Spring Cloud Functions, or if not, what (if anything) could we do to enable this.

Resources:

- https://spring.io/blog/2017/07/05/introducing-spring-cloud-function
- Sample: https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-aws

**Comment by XerTheSquirrel** [comment]
Okay, I have taken a slight glance at this. From the looks of it creating a wrapper for Spring will be similar to `SimpleRequestHandlerWrapper` except with some differences. It seems like that mixing of Spring, AWS, and IOpipe will be a bit complicated at first to figure out how to best fit them together so that the user does not have any issues using IOpipe with their Spring functions. From the looks of it though this probably should go into another repository since including Spring could bloat the base library up and a library specific for Spring would probably be the best. There would just be the IOpipe variants of these wrappers, so they would be like wrappers on top of wrappers. Additionally because of the issues with release handling for the examples could probably be avoided from the start. The Spring package would just need to be updated for version numbers every time a release is made.

I would also want to have it where the event-info project I am working on can additionally support Spring and provide those events accordingly.

**Comment by XerTheSquirrel** [comment]
Okay so the the repository to look at is https://github.com/spring-cloud/spring-cloud-function . However right now I am having some issues building it and it seems to be quite in beta. Currently M5 works and M6 is broken (it just tries to download every single AWS SDK version).

One potential issue is this issue https://github.com/spring-cloud/spring-cloud-function/issues/167 which specifies that `Context` is not accessible, this would be slightly problematic as things which are in the `Context` are rather needed. There may be a need for agnostic context information.

**Comment by XerTheSquirrel** [comment]
Going to set this as blocked until there is an actual release, that way there is a stable base to check and develop for.

**Comment by XerTheSquirrel** [comment]
Okay this is currently in the release candidate phase (RC2 as per https://github.com/spring-cloud/spring-cloud-function/releases/tag/v1.0.0.RC2 ).

**Comment by XerTheSquirrel** [comment]
Okay it was released 12 days ago (https://github.com/spring-cloud/spring-cloud-function/releases/tag/v1.0.0.RELEASE).

**Comment by XerTheSquirrel** [comment]
They still do not provide access to the AWS `Context` object, so will probably have to extract all the information it gives such as the ARN, function name, etc. if those are even available for IOpipe to report on.

**Comment by XerTheSquirrel** [comment]
Blocked by #163.

**Comment by XerTheSquirrel** [comment]
So far from tests:

 1. Followed example at https://dzone.com/articles/run-code-with-spring-cloud-function-on-aws-lambda
 2. Initialized project based off https://github.com/laxika/spring-cloud-function-aws-example
 3. Removed `provided` scope from `aws-lambda-java-events` and `aws-lambda-java-log4j` because they are no longer actually provided by AWS and will cause missing class errors.
 4. Upgraded `org.springframework.cloud:spring-cloud-function-adapter-aws` to `2.0.0.M1`
 5. Added dependency `com.iopipe:iopipe` at version `1.7.0`.

The example without wrapping IOpipe works albeit with a very high coldstart time (11s on 512MB).

This fails to work with IOpipe because #163, the base class `requestHandler` has only generic types and they must be determined by looking through the class hierarchy.

**Comment by XerTheSquirrel** [comment]
With #163 merged, this works with the generic entry point handler with no issues that I can find.

**Comment by XerTheSquirrel** [comment]
Since it was merged, this will work with 1.8.0 when it is released. Will be closing.
